name: Yujung Lee
author: Yujung Lee
baseurl: 
description: 
github: https://yujungl.github.io/
twitter: http://www.twitter.com/
facebook: http://www.facebook.com
linkedin: http://www.linkedin.com
email: dldbwjd7579@gmail.com
location: 42°2'16"N   70°12'47"W
disqus: 

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
